# build environment: run https://mherman.org/blog/dockerizing-a-react-app/

FROM node:16.16.0 as build
WORKDIR /app
COPY .npmrc .npmrc 
COPY package-lock.json .
COPY package.json .
RUN npm ci
COPY . .
RUN npm run build --profile


# production environment
FROM nginx
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html/dms
COPY docker/config.js /usr/share/nginx/html/dms
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]