const transformerMenuConf: any = {
    'Input/Output': {
        category: 'Input/Output',
        order: 1,
        icon: "TransformersIcon",
        backgroundDark: "#C9C5E9",
        backgroundLight: "#ECEAFD",
        backgroundLightStroke: "#9792C8",
        backgroundDarkStroke: "#C9C5E9",

    },
    'Anomaly Detection/Imputation': {
        category: 'Anomaly Detection/Imputation',
        order: 4,
        icon: "AnomalyDetectionIcon",
        backgroundDark: "#83C7FB",
        backgroundLight: "#E3F7FA",
        backgroundLightStroke: "#97C2C9",
        backgroundDarkStroke: "#83C7FB",

    },
    'Promotion Model': {
        category: 'Promotion Model',
        order: 3,
        icon: "PromotionModelsIcon",
        backgroundDark: "#FFC2C8",
        backgroundLight: "#FEEBEE",
        backgroundLightStroke: "#C0999F",
        backgroundDarkStroke: "#FFC2C8",
    },
    'Time-Series Models': {
        category: 'Time-Series Models',
        order: 2,
        icon: "TimeSeriesModelsIcon",
        backgroundDark: "#E9E5CB",
        backgroundLight: "#FDFBEA",
        backgroundLightStroke: "#C9C49C",
        backgroundDarkStroke: "#E9E5CB",

    },
    'Feature Extraction': {
        category: 'Feature Extraction',
        order: 5,
        icon: "FeatureExtractionIcon",
        backgroundDark: "#F6C99F",
        backgroundLight: "#FBF3E3",
        backgroundLightStroke: "#DAC8A1",
        backgroundDarkStroke: "#F6C99F",
    },
    'Dataframe Manipulation': {
        category: 'Dataframe Manipulation',
        order: 6,
        icon: "DataFrameManipulationIcon",
        backgroundDark: "#80E0C0",
        backgroundLight: "#F1FFF2",
        backgroundLightStroke: "#53AC59",
        backgroundDarkStroke: "#80E0C0",
    },
    'Aggregation/Disaggregation': {
        category: 'Aggregation/Disaggregation',
        order: 7,
        icon: "AggregationDisaggregationIcon",
        backgroundDark: "#B9B8FF",
        backgroundLight: "#ECF5FF",
        backgroundLightStroke: "#5686BD",
        backgroundDarkStroke: "#B9B8FF",
    },
    'Artificial Neural Network': {
        category: 'Artificial Neural Network',
        order: 8,
        icon: "ArtificialNeuralNetworkIcon",
        backgroundDark: "#EDEDED",
        backgroundLight: "#EDEDED",
        backgroundLightStroke: "#C1BDBD",
        backgroundDarkStroke: "#EDEDED",
    },
    'Key Performance Indicator': {
        category: 'Key Performance Indicator',
        order: 9,
        icon: "KeyPerformanceIndicatorIcon",
        backgroundDark: "#CEE095",
        backgroundLight: "#F8FFE9",
        backgroundLightStroke: "#BEC8A9",
        backgroundDarkStroke: "#CEE095",
    },
    'Machine Learning Models': {
        category: 'Machine Learning Models',
        order: 10,
        icon: "MachineLearningModelsIcon",
        backgroundDark: "#F9BFFF",
        backgroundLight: "#FFF6F0",
        backgroundLightStroke: "#A75A2E",
        backgroundDarkStroke: "#F9BFFF",
    },
    'Custom Transformers': {
        category: 'Custom Transformers',
        order: 11,
        icon: "CustomTransformersIcon",
        backgroundDark: "#C1E0EB",
        backgroundLight: "#E8F4F4",
        backgroundLightStroke: "#90B9BF",
        backgroundDarkStroke: "#C1E0EB",
    },
}
export default transformerMenuConf;
